package:
    type:           yii2-extension
    name:           hidev-phpunit
    title:          PHPUnit plugin for HiDev
    headline:       HiDev PHPUnit
    keywords:       phpunit, hidev, plugin
    namespace:      hidev\phpunit
    description:    |
        [HiDev](https://github.com/hiqdev/hidev) is a task runner, code generator and build tool for easier continuous integration.

        This plugin enables [PHPUnit](https://phpunit.de/) support for HiDev.

        Provides usual PHPUnit operations:

        - generating phpunit.xml.dist and tests/_bootstrap.php
        - running tests
        - tries to create your tests compatible with Codeception
        - enables coverage report
        - generating skeleton tests with [phpunit-skeleton-generator](https://github.com/sebastianbergmann/phpunit-skeleton-generator) (in progress)

require:
    hiqdev/hidev-php:           "*@dev"
    hiqdev/hidev-readme:        "*@dev"
    hiqdev/hidev-travis:        "*@dev"
    hiqdev/hidev-vendor:        "*@dev"
    hiqdev/hidev-license:       "*@dev"
    hiqdev/hidev-phpunit:       "*@dev"
    hiqdev/hidev-composer:      "*@dev"
    hiqdev/hidev-scrutinizer:   "*@dev"
    hiqdev/hidev-php-cs-fixer:  "*@dev"
